window.PROJECTS = [
  {id:'qingdong',title:'Qingdong: AI Movement Coach',en:'轻动',year:'2026.08',role:'Product Strategy · Interaction Design',categories:['product','strategy'],image:'../assets/projects/qingdong-demo-poster.jpg',video:'../assets/videos/qingdong-demo.mp4',videoPoster:'../assets/projects/qingdong-demo-poster.jpg',summary:'An end-to-end flow from Douyin Feed discovery and camera-based motion recognition to Doubao coaching feedback and shareable results, enabling a 50-second seated movement break; Top 10 at the Douyin AI Innovators Hackathon Shenzhen Regional.',metrics:[['TOP 10','Shenzhen Regional'],['50 sec','Movement experience'],['Feed→AI','End-to-end loop']],tags:['AI Product','Motion Recognition','Mini Program','UX Design']},
  {id:'jingmeng',title:'Jingmeng: Finding Du Liniang',en:'惊梦：寻回杜丽娘',year:'2026.07',role:'Product Lead',categories:['product','culture'],repo:'https://github.com/hisnyaoyang-web/VRmudanting-jingmeng',image:'../assets/projects/jingmeng-cover.jpg',video:'../assets/videos/jingmeng-demo.mp4',videoPoster:'../assets/projects/jingmeng-cover.jpg',link:'https://vrmudanting-jingmeng-d06h51vde-hisnyaoyang-2167s-projects.vercel.app/',linkNote:'VPN required',summary:'A web-based interactive experience centered on Du Liniang from The Peony Pavilion, honored in two tracks at AdventureX 2026 and now live online.',metrics:[['First Prize','PICO Best Web App Creator'],['Third Prize','HoYoverse track'],['5 days','Hackathon delivery']],tags:['Product','Web','VR','Cultural Tech']},
  {id:'cyber-ancestor',title:'Cyber Ancestor',en:'赛博老祖宗养成计划',year:'2026',role:'Project Lead · AI Product · Full-stack',categories:['product','strategy','growth'],image:'../assets/projects/cyber-ancestor.jpg',video:'../assets/videos/cyber-ancestor.mp4',summary:'Turning historical figures into an AI companion you can raise, talk with, and share.',metrics:[['40%','Chapter-2 completion lift'],['8 min','Avg. interaction time'],['25%','Beta share rate']],tags:['AI Agent','Prompt','A/B Test','Full-stack']},
  {id:'moonbot',title:'Moonbot Tutor',en:'Moonbot Tutor',year:'2026',role:'AI Product Lead',categories:['product'],image:'../assets/projects/moonbot-cover.jpg',video:'../assets/videos/moonbot.mp4',summary:'Automatically turning any question into a teaching video or interactive HTML page.',metrics:[['7-stage','Automated pipeline'],['2 modes','HTML + video'],['3 models','Multi-model orchestration']],tags:['AI Pipeline','Claude','TTS','ManimCE']},
  {id:'gushu-mask',title:'Ancient Shu Digital Mask',en:'古蜀覆面：三星堆数字神面',year:'2026',role:'Project Lead · Full-stack',categories:['product','culture'],image:'../assets/projects/gushu-mask-cover.jpg',video:'../assets/videos/gushu-mask.mp4',summary:'AI design, 3D modeling, and AR try-on that let anyone forge their own Sanxingdui divine mask.',metrics:[['1st','Nextstep First Prize'],['AI→3D','Multimodal pipeline'],['AR','Motion interaction']],tags:['Generative AI','3D','AR','Cultural Tech']},
  {id:'heritage',title:'Intelligent Heritage Computing',en:'文化遗产智能计算',year:'2025—Present',role:'Provincial Innovation Program Lead',categories:['culture'],image:'../assets/projects/heritage-computing.png',summary:'Turning artifact motifs from raw pixels into computable units that carry cultural semantics.',metrics:[['Provincial','Innovation program'],['SAM','Semantic segmentation'],['Cross-modal','Image–text mapping']],tags:['Digital Humanities','SAM','Annotation','Multimodal']},
  {id:'gusu',title:'Prosperous Suzhou, Reanimated',en:'《姑苏繁华图》数字活化',year:'2025',role:'Independent research · Narrative design · Development',categories:['culture'],image:'../assets/projects/gusu-cover.jpg',video:'../assets/videos/gusu-scroll.mp4',link:'http://82.157.189.119/',summary:'Re-entering an ancient city scroll through three identities: merchant, literatus, and commoner. Winner of the poster competition at Oxford DHOxSS 2026.',metrics:[['Winner','Oxford DHOxSS 2026 poster competition'],['3','Identity perspectives'],['Scroll','Scroll interaction']],tags:['Digital Heritage','Narrative','Interaction']},
  {id:'sushi',title:'Su Shi & Su Zhe Sentiment',en:'二苏诗词情感识别',year:'2025',role:'Independent product design & full-stack development',categories:['product','culture'],image:'../assets/projects/sushi-sentiment.jpg',video:'../assets/videos/sushi-sentiment.mp4',summary:'LLM-based sentiment annotation and visualization that turn classical poetry into an explorable data experience.',metrics:[['NLP','Sentiment detection'],['LLM','Text annotation'],['Web','Interactive visualization']],tags:['AI Product','Digital Humanities','NLP','Visualization']},
  {id:'children-edu',title:'Children Education Tool',en:'儿童公益教学工具',year:'2025',role:'Independent product design & full-stack development',categories:['product','strategy'],image:'../assets/projects/children-education.jpg',video:'../assets/videos/children-education.mp4',summary:'Replacing scattered WeChat-group check-ins with structured records and data dashboards.',metrics:[['+50%','Module dwell time'],['+20%','Weekly retention'],['+30%','Comprehension accuracy']],tags:['User Research','Dashboard','Education','Full-stack']},
  {id:'lingya',title:'Tencent Lingya Campus Growth',en:'腾讯灵芽 AIGC 产品运营',year:'2026.05—Aug 2026',role:'Campus Ambassador · Product Ops',categories:['strategy','growth'],summary:'Building campus acquisition and seed-creator incubation from 0 to 1.',metrics:[['2,000+','Campus reach'],['75%','Course completion'],['180','Organic signups']],tags:['Growth','Creator Ops','Feedback Loop','AIGC']},
  {id:'douyin',title:'WHU Douyin Club',en:'武汉大学抖音俱乐部',year:'2025',role:'Editor-in-Chief & Lead',categories:['growth'],image:'../assets/projects/douyin-club.png',summary:'Building a recognizable campus account and community on the strength of campus-life resonance.',gallery:[{image:'../assets/projects/douyin-account-operations.jpg',caption:'Account operations, Mar–Aug 2025: 1M+ cumulative plays, 10K+ likes, top video at 878K plays'},{image:'../assets/projects/douyin-event-planning.jpg',caption:'Event planning documents: concert booth plan, “Tracing WHU” and “Luojia Trail Run” themed event proposals'},{image:'../assets/projects/douyin-sakura-event.jpg',caption:'ByteDance cherry-blossom season event: planned the event and coordinated volunteers; 20,745 livestream views and an estimated 10K+ on-site audience'}],metrics:[['878K','Top video plays'],['1M+','Total plays'],['20K+','Sakura livestream views']],tags:['Content Strategy','Community','Data']},
  {id:'hi-acho',title:'NetEase Hi Acho User Research',en:'网易 Hi Acho 用户研究',year:'2025',role:'User Research Lead',categories:['strategy'],image:'../assets/projects/hi-acho.png',summary:'Locating the experience gaps of an AI spoken-English product through surveys and in-depth interviews.',metrics:[['1,022','Valid responses'],['20+','In-depth interviews'],['4','Cities covered']],tags:['User Research','SPSS','Interview','AI Education']},
  {id:'personal-content',title:'Personal Content Growth',en:'个人账号内容增长',year:'2025—Present',role:'Solo operator',categories:['growth'],image:'../assets/projects/personal-content-cover.jpg',summary:'Validating cold-start paths for scenario-based content and social virality from 0 to 1.',metrics:[['110K+','Top Channels play'],['700%','7-day follower growth'],['18K+','Top XHS post views']],tags:['Cold Start','A/B Test','Social Growth']}
];
