const projectById=id=>window.PROJECTS.find(p=>p.id===id);
const categoryName={product:'AI PRODUCT',research:'DIGITAL HUMANITIES',operations:'GROWTH & OPERATIONS'};
const cardMarkup=p=>`<a class="project-card" href="project.html?id=${p.id}" data-categories="${p.categories.join(' ')}"><div class="project-visual ${p.image?'':'no-image'}">${p.image?`<img src="${p.image}" alt="${p.title}" loading="lazy">`:''}<span>${p.categories.map(c=>categoryName[c]).join(' · ')}</span></div><div class="project-body"><p class="kicker">${p.year} · ${p.role}</p><h3>${p.title}</h3><p>${p.summary}</p><div class="tag-list">${p.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div></div></a>`;
const recMarkup=(p,index)=>`<a class="rec-card" href="project.html?id=${p.id}"><span>0${index+1}</span><div><h4>${p.title}</h4><p>${p.summary}</p></div><b>↗</b></a>`;
function setView(view){const data=window.AUDIENCE_VIEWS[view];document.querySelector('#recommended').innerHTML=data.projects.map(projectById).map(recMarkup).join('');document.querySelectorAll('[data-view]').forEach(button=>{const active=button.dataset.view===view;button.classList.toggle('active',active);button.setAttribute('aria-selected',String(active))})}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));setView('product');
const grid=document.querySelector('#project-grid');grid.innerHTML=window.PROJECTS.map(cardMarkup).join('');document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{const filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b===button));grid.querySelectorAll('.project-card').forEach(card=>card.hidden=filter!=='all'&&!card.dataset.categories.split(' ').includes(filter))}));
const menu=document.querySelector('.menu'),nav=document.querySelector('#nav');menu?.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open))});nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.07});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));document.querySelector('#year').textContent=new Date().getFullYear();
